package bean;
// Generated 14/12/2025 15:05:49 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="db_isadora_amaral"
)
public class Clientes  implements java.io.Serializable {


     private int iaaIdCliente;
     private String iaaNome;
     private String iaaApelido;
     private char iaaSexoFeminino;
     private char iaaSexoMasculino;
     private Date iaaDataNascimento;
     private String iaaCpf;
     private String iaaEmail;
     private String iaaTelefone;
     private String iaaEndereco;
     private String iaaCidade;
     private String iaaPais;
     private String iaaCep;
     private String iaaSenha;
     private Date iaaDataCadastro;
     private String iaaAtivo;

    public Clientes() {
    }

	
    public Clientes(int iaaIdCliente, String iaaNome, String iaaApelido, char iaaSexoFeminino, char iaaSexoMasculino, String iaaCpf, String iaaEmail, String iaaTelefone, String iaaEndereco, String iaaCidade, String iaaPais, String iaaCep, String iaaSenha, String iaaAtivo) {
        this.iaaIdCliente = iaaIdCliente;
        this.iaaNome = iaaNome;
        this.iaaApelido = iaaApelido;
        this.iaaSexoFeminino = iaaSexoFeminino;
        this.iaaSexoMasculino = iaaSexoMasculino;
        this.iaaCpf = iaaCpf;
        this.iaaEmail = iaaEmail;
        this.iaaTelefone = iaaTelefone;
        this.iaaEndereco = iaaEndereco;
        this.iaaCidade = iaaCidade;
        this.iaaPais = iaaPais;
        this.iaaCep = iaaCep;
        this.iaaSenha = iaaSenha;
        this.iaaAtivo = iaaAtivo;
    }
    public Clientes(int iaaIdCliente, String iaaNome, String iaaApelido, char iaaSexoFeminino, char iaaSexoMasculino, Date iaaDataNascimento, String iaaCpf, String iaaEmail, String iaaTelefone, String iaaEndereco, String iaaCidade, String iaaPais, String iaaCep, String iaaSenha, Date iaaDataCadastro, String iaaAtivo) {
       this.iaaIdCliente = iaaIdCliente;
       this.iaaNome = iaaNome;
       this.iaaApelido = iaaApelido;
       this.iaaSexoFeminino = iaaSexoFeminino;
       this.iaaSexoMasculino = iaaSexoMasculino;
       this.iaaDataNascimento = iaaDataNascimento;
       this.iaaCpf = iaaCpf;
       this.iaaEmail = iaaEmail;
       this.iaaTelefone = iaaTelefone;
       this.iaaEndereco = iaaEndereco;
       this.iaaCidade = iaaCidade;
       this.iaaPais = iaaPais;
       this.iaaCep = iaaCep;
       this.iaaSenha = iaaSenha;
       this.iaaDataCadastro = iaaDataCadastro;
       this.iaaAtivo = iaaAtivo;
    }
   
     @Id 

    
    @Column(name="iaaIdCliente", unique=true, nullable=false)
    public int getIaaIdCliente() {
        return this.iaaIdCliente;
    }
    
    public void setIaaIdCliente(int iaaIdCliente) {
        this.iaaIdCliente = iaaIdCliente;
    }

    
    @Column(name="iaaNome", nullable=false, length=100)
    public String getIaaNome() {
        return this.iaaNome;
    }
    
    public void setIaaNome(String iaaNome) {
        this.iaaNome = iaaNome;
    }

    
    @Column(name="iaaApelido", nullable=false, length=20)
    public String getIaaApelido() {
        return this.iaaApelido;
    }
    
    public void setIaaApelido(String iaaApelido) {
        this.iaaApelido = iaaApelido;
    }

    
    @Column(name="iaaSexoFeminino", nullable=false, length=1)
    public char getIaaSexoFeminino() {
        return this.iaaSexoFeminino;
    }
    
    public void setIaaSexoFeminino(char iaaSexoFeminino) {
        this.iaaSexoFeminino = iaaSexoFeminino;
    }

    
    @Column(name="iaaSexoMasculino", nullable=false, length=1)
    public char getIaaSexoMasculino() {
        return this.iaaSexoMasculino;
    }
    
    public void setIaaSexoMasculino(char iaaSexoMasculino) {
        this.iaaSexoMasculino = iaaSexoMasculino;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="iaaDataNascimento", length=10)
    public Date getIaaDataNascimento() {
        return this.iaaDataNascimento;
    }
    
    public void setIaaDataNascimento(Date iaaDataNascimento) {
        this.iaaDataNascimento = iaaDataNascimento;
    }

    
    @Column(name="iaaCpf", nullable=false, length=14)
    public String getIaaCpf() {
        return this.iaaCpf;
    }
    
    public void setIaaCpf(String iaaCpf) {
        this.iaaCpf = iaaCpf;
    }

    
    @Column(name="iaaEmail", nullable=false, length=50)
    public String getIaaEmail() {
        return this.iaaEmail;
    }
    
    public void setIaaEmail(String iaaEmail) {
        this.iaaEmail = iaaEmail;
    }

    
    @Column(name="iaaTelefone", nullable=false, length=15)
    public String getIaaTelefone() {
        return this.iaaTelefone;
    }
    
    public void setIaaTelefone(String iaaTelefone) {
        this.iaaTelefone = iaaTelefone;
    }

    
    @Column(name="iaaEndereco", nullable=false, length=15)
    public String getIaaEndereco() {
        return this.iaaEndereco;
    }
    
    public void setIaaEndereco(String iaaEndereco) {
        this.iaaEndereco = iaaEndereco;
    }

    
    @Column(name="iaaCidade", nullable=false, length=100)
    public String getIaaCidade() {
        return this.iaaCidade;
    }
    
    public void setIaaCidade(String iaaCidade) {
        this.iaaCidade = iaaCidade;
    }

    
    @Column(name="iaaPais", nullable=false, length=100)
    public String getIaaPais() {
        return this.iaaPais;
    }
    
    public void setIaaPais(String iaaPais) {
        this.iaaPais = iaaPais;
    }

    
    @Column(name="iaaCep", nullable=false, length=9)
    public String getIaaCep() {
        return this.iaaCep;
    }
    
    public void setIaaCep(String iaaCep) {
        this.iaaCep = iaaCep;
    }

    
    @Column(name="iaaSenha", nullable=false, length=20)
    public String getIaaSenha() {
        return this.iaaSenha;
    }
    
    public void setIaaSenha(String iaaSenha) {
        this.iaaSenha = iaaSenha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="iaaDataCadastro", length=10)
    public Date getIaaDataCadastro() {
        return this.iaaDataCadastro;
    }
    
    public void setIaaDataCadastro(Date iaaDataCadastro) {
        this.iaaDataCadastro = iaaDataCadastro;
    }

    
    @Column(name="iaaAtivo", nullable=false, length=1)
    public String getIaaAtivo() {
        return this.iaaAtivo;
    }
    
    public void setIaaAtivo(String iaaAtivo) {
        this.iaaAtivo = iaaAtivo;
    }

}


