package bean;
// Generated 14/12/2025 15:05:49 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historicoatendimento generated by hbm2java
 */
@Entity
@Table(name = "historicoatendimento", catalog = "db_isadora_amaral"
)
public class Historicoatendimento implements java.io.Serializable {

    private int iaaIdAtendimento;
    private Clientes iaaIdClientes;
    private Usuarios iaaIdUsuarios;
    private Date iaaDataAtendimento;
    private String iaaTipoAtendimento;
    private String iaaDescricao;
    private Double iaaValor;

    public Historicoatendimento() {
    }

    public Historicoatendimento(int iaaIdAtendimento, Clientes iaaIdClientes, Usuarios iaaIdUsuarios, String iaaTipoAtendimento, String iaaDescricao) {
        this.iaaIdAtendimento = iaaIdAtendimento;
        this.iaaIdClientes = iaaIdClientes;
        this.iaaIdUsuarios = iaaIdUsuarios;
        this.iaaTipoAtendimento = iaaTipoAtendimento;
        this.iaaDescricao = iaaDescricao;
    }

    public Historicoatendimento(int iaaIdAtendimento, Clientes iaaIdClientes, Usuarios iaaIdUsuarios, Date iaaDataAtendimento, String iaaTipoAtendimento, String iaaDescricao, Double iaaValor) {
        this.iaaIdAtendimento = iaaIdAtendimento;
        this.iaaIdClientes = iaaIdClientes;
        this.iaaIdUsuarios = iaaIdUsuarios;
        this.iaaDataAtendimento = iaaDataAtendimento;
        this.iaaTipoAtendimento = iaaTipoAtendimento;
        this.iaaDescricao = iaaDescricao;
        this.iaaValor = iaaValor;
    }

    @Id

    @Column(name = "iaaIdAtendimento", unique = true, nullable = false)
    public int getIaaIdAtendimento() {
        return this.iaaIdAtendimento;
    }

    public void setIaaIdAtendimento(int iaaIdAtendimento) {
        this.iaaIdAtendimento = iaaIdAtendimento;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "iaaIdCliente", nullable = false)
    public Clientes getIaaIdClientes() {
        return this.iaaIdClientes;
    }

    public void setIaaIdClientes(Clientes iaaIdClientes) {
        this.iaaIdClientes = iaaIdClientes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "iaaIdUsuarios", nullable = false)
    public Usuarios getIaaIdUsuarios() {
        return this.iaaIdUsuarios;
    }

    public void setIaaIdUsuarios(Usuarios iaaIdUsuarios) {
        this.iaaIdUsuarios = iaaIdUsuarios;
    }

    @Column(name = "iaaDataAtendimento", length = 19)
    @Temporal(javax.persistence.TemporalType.DATE)
    public Date getIaaDataAtendimento() {
        return this.iaaDataAtendimento;
    }

    public void setIaaDataAtendimento(Date iaaDataAtendimento) {
        this.iaaDataAtendimento = iaaDataAtendimento;
    }

    @Column(name = "iaaTipoAtendimento", nullable = false, length = 50)
    public String getIaaTipoAtendimento() {
        return this.iaaTipoAtendimento;
    }

    public void setIaaTipoAtendimento(String iaaTipoAtendimento) {
        this.iaaTipoAtendimento = iaaTipoAtendimento;
    }

    @Column(name = "iaaDescricao", nullable = false, length = 50)
    public String getIaaDescricao() {
        return this.iaaDescricao;
    }

    public void setIaaDescricao(String iaaDescricao) {
        this.iaaDescricao = iaaDescricao;
    }

    @Column(name = "iaaValor", precision = 10)
    public Double getIaaValor() {
        return this.iaaValor;
    }

    public void setIaaValor(Double iaaValor) {
        this.iaaValor = iaaValor;
    }

}
