package bean;
// Generated 08/10/2025 17:03:02 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historicoatendimento generated by hbm2java
 */
@Entity
@Table(name="historicoatendimento"
    ,catalog="db_isadora_amaral"
)
public class Historicoatendimento  implements java.io.Serializable {


     private int iaaIdAtendimento;
     private Integer iaaIdCliente;
     private Date iaaDataAtendimento;
     private String iaaTipoAtendimento;
     private String iaaDescricao;
     private String iaaAtendente;
     private Double iaaValor;

    public Historicoatendimento() {
    }

	
    public Historicoatendimento(int iaaIdAtendimento, String iaaTipoAtendimento, String iaaDescricao, String iaaAtendente) {
        this.iaaIdAtendimento = iaaIdAtendimento;
        this.iaaTipoAtendimento = iaaTipoAtendimento;
        this.iaaDescricao = iaaDescricao;
        this.iaaAtendente = iaaAtendente;
    }
    public Historicoatendimento(int iaaIdAtendimento, Integer iaaIdCliente, Date iaaDataAtendimento, String iaaTipoAtendimento, String iaaDescricao, String iaaAtendente, Double iaaValor) {
       this.iaaIdAtendimento = iaaIdAtendimento;
       this.iaaIdCliente = iaaIdCliente;
       this.iaaDataAtendimento = iaaDataAtendimento;
       this.iaaTipoAtendimento = iaaTipoAtendimento;
       this.iaaDescricao = iaaDescricao;
       this.iaaAtendente = iaaAtendente;
       this.iaaValor = iaaValor;
    }
   
     @Id 

    
    @Column(name="iaaIdAtendimento", unique=true, nullable=false)
    public int getIaaIdAtendimento() {
        return this.iaaIdAtendimento;
    }
    
    public void setIaaIdAtendimento(int iaaIdAtendimento) {
        this.iaaIdAtendimento = iaaIdAtendimento;
    }

    
    @Column(name="iaaIdCliente")
    public Integer getIaaIdCliente() {
        return this.iaaIdCliente;
    }
    
    public void setIaaIdCliente(Integer iaaIdCliente) {
        this.iaaIdCliente = iaaIdCliente;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="iaaDataAtendimento", length=19)
    public Date getIaaDataAtendimento() {
        return this.iaaDataAtendimento;
    }
    
    public void setIaaDataAtendimento(Date iaaDataAtendimento) {
        this.iaaDataAtendimento = iaaDataAtendimento;
    }

    
    @Column(name="iaaTipoAtendimento", nullable=false, length=50)
    public String getIaaTipoAtendimento() {
        return this.iaaTipoAtendimento;
    }
    
    public void setIaaTipoAtendimento(String iaaTipoAtendimento) {
        this.iaaTipoAtendimento = iaaTipoAtendimento;
    }

    
    @Column(name="iaaDescricao", nullable=false, length=65535)
    public String getIaaDescricao() {
        return this.iaaDescricao;
    }
    
    public void setIaaDescricao(String iaaDescricao) {
        this.iaaDescricao = iaaDescricao;
    }

    
    @Column(name="iaaAtendente", nullable=false, length=50)
    public String getIaaAtendente() {
        return this.iaaAtendente;
    }
    
    public void setIaaAtendente(String iaaAtendente) {
        this.iaaAtendente = iaaAtendente;
    }

    
    @Column(name="iaaValor", precision=22, scale=0)
    public Double getIaaValor() {
        return this.iaaValor;
    }
    
    public void setIaaValor(Double iaaValor) {
        this.iaaValor = iaaValor;
    }




}


