package bean;
// Generated 14/12/2025 15:05:49 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produtos generated by hbm2java
 */
@Entity
@Table(name="produtos"
    ,catalog="db_isadora_amaral"
)
public class Produtos  implements java.io.Serializable {


     private int iaaIdProdutos;
     private String iaaNome;
     private String iaaTamanho;
     private Double iaaPreco;
     private int iaaEstoque;
     private String iaaCategoria;
     private String iaaDescricao;

    public Produtos() {
    }

	
    public Produtos(int iaaIdProdutos, String iaaNome, String iaaTamanho, Double iaaPreco, int iaaEstoque, String iaaCategoria, String iaaDescricao) {
        this.iaaIdProdutos = iaaIdProdutos;
        this.iaaNome = iaaNome;
        this.iaaTamanho = iaaTamanho;
        this.iaaPreco = iaaPreco;
        this.iaaEstoque = iaaEstoque;
        this.iaaCategoria = iaaCategoria;
        this.iaaDescricao = iaaDescricao;
    }
   
     @Id 

    
    @Column(name="iaaIdProdutos", unique=true, nullable=false)
    public int getIaaIdProdutos() {
        return this.iaaIdProdutos;
    }
    
    public void setIaaIdProdutos(int iaaIdProdutos) {
        this.iaaIdProdutos = iaaIdProdutos;
    }

    
    @Column(name="iaaNome", nullable=false, length=50)
    public String getIaaNome() {
        return this.iaaNome;
    }
    
    public void setIaaNome(String iaaNome) {
        this.iaaNome = iaaNome;
    }

    
    @Column(name="iaaTamanho", nullable=false, length=200)
    public String getIaaTamanho() {
        return this.iaaTamanho;
    }
    
    public void setIaaTamanho(String iaaTamanho) {
        this.iaaTamanho = iaaTamanho;
    }

    
    @Column(name="iaaPreco", nullable=false, precision=10)
    public Double getIaaPreco() {
        return this.iaaPreco;
    }
    
    public void setIaaPreco(Double iaaPreco) {
        this.iaaPreco = iaaPreco;
    }

    
    @Column(name="iaaEstoque", nullable=false)
    public int getIaaEstoque() {
        return this.iaaEstoque;
    }
    
    public void setIaaEstoque(int iaaEstoque) {
        this.iaaEstoque = iaaEstoque;
    }

    
    @Column(name="iaaCategoria", nullable=false, length=50)
    public String getIaaCategoria() {
        return this.iaaCategoria;
    }
    
    public void setIaaCategoria(String iaaCategoria) {
        this.iaaCategoria = iaaCategoria;
    }

    
    @Column(name="iaaDescricao", nullable=false, length=50)
    public String getIaaDescricao() {
        return this.iaaDescricao;
    }
    
    public void setIaaDescricao(String iaaDescricao) {
        this.iaaDescricao = iaaDescricao;
    }

    @Override
    public String toString() {
        return this.getIaaNome();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof Produtos) {
            Produtos o = (Produtos) obj;
            if (o.getIaaIdProdutos()== this.getIaaIdProdutos()) {
                return true;
            }
        }
        return false;
    }
}


