package bean;
// Generated 08/10/2025 17:03:02 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="db_isadora_amaral"
)
public class Usuarios  implements java.io.Serializable {


     private int iaaIdUsuarios;
     private String iaaNome;
     private String iaaApelido;
     private String iaaCpf;
     private Date iaaDataNascimento;
     private String iaaSenha;
     private int iaaNivel;
     private String iaaAtivo;

    public Usuarios() {
    }

	
    public Usuarios(int iaaIdUsuarios, String iaaNome, String iaaApelido, String iaaCpf, String iaaSenha, int iaaNivel, String iaaAtivo) {
        this.iaaIdUsuarios = iaaIdUsuarios;
        this.iaaNome = iaaNome;
        this.iaaApelido = iaaApelido;
        this.iaaCpf = iaaCpf;
        this.iaaSenha = iaaSenha;
        this.iaaNivel = iaaNivel;
        this.iaaAtivo = iaaAtivo;
    }
    public Usuarios(int iaaIdUsuarios, String iaaNome, String iaaApelido, String iaaCpf, Date iaaDataNascimento, String iaaSenha, int iaaNivel, String iaaAtivo) {
       this.iaaIdUsuarios = iaaIdUsuarios;
       this.iaaNome = iaaNome;
       this.iaaApelido = iaaApelido;
       this.iaaCpf = iaaCpf;
       this.iaaDataNascimento = iaaDataNascimento;
       this.iaaSenha = iaaSenha;
       this.iaaNivel = iaaNivel;
       this.iaaAtivo = iaaAtivo;
    }
   
     @Id 

    
    @Column(name="iaaIdUsuarios", unique=true, nullable=false)
    public int getIaaIdUsuarios() {
        return this.iaaIdUsuarios;
    }
    
    public void setIaaIdUsuarios(int iaaIdUsuarios) {
        this.iaaIdUsuarios = iaaIdUsuarios;
    }

    
    @Column(name="iaaNome", nullable=false, length=50)
    public String getIaaNome() {
        return this.iaaNome;
    }
    
    public void setIaaNome(String iaaNome) {
        this.iaaNome = iaaNome;
    }

    
    @Column(name="iaaApelido", nullable=false, length=20)
    public String getIaaApelido() {
        return this.iaaApelido;
    }
    
    public void setIaaApelido(String iaaApelido) {
        this.iaaApelido = iaaApelido;
    }

    
    @Column(name="iaaCpf", nullable=false, length=11)
    public String getIaaCpf() {
        return this.iaaCpf;
    }
    
    public void setIaaCpf(String iaaCpf) {
        this.iaaCpf = iaaCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="iaaDataNascimento", length=10)
    public Date getIaaDataNascimento() {
        return this.iaaDataNascimento;
    }
    
    public void setIaaDataNascimento(Date iaaDataNascimento) {
        this.iaaDataNascimento = iaaDataNascimento;
    }

    
    @Column(name="iaaSenha", nullable=false, length=20)
    public String getIaaSenha() {
        return this.iaaSenha;
    }
    
    public void setIaaSenha(String iaaSenha) {
        this.iaaSenha = iaaSenha;
    }

    
    @Column(name="iaaNivel", nullable=false)
    public int getIaaNivel() {
        return this.iaaNivel;
    }
    
    public void setIaaNivel(int iaaNivel) {
        this.iaaNivel = iaaNivel;
    }

    
    @Column(name="iaaAtivo", nullable=false, length=1)
    public String getIaaAtivo() {
        return this.iaaAtivo;
    }
    
    public void setIaaAtivo(String iaaAtivo) {
        this.iaaAtivo = iaaAtivo;
    }




}


