package bean;
// Generated 14/12/2025 15:05:49 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vendaproduto generated by hbm2java
 */
@Entity
@Table(name="vendaproduto"
    ,catalog="db_isadora_amaral"
)
public class Vendaproduto  implements java.io.Serializable {


     private VendaprodutoId id;
     private Produtos produtos;
     private Vendas vendas;
     private int iaaQuantidade;
     private Double iaaValor;
     private Double iaaDesconto;

    public Vendaproduto() {
    }

	
    public Vendaproduto(VendaprodutoId id, Produtos produtos, Vendas vendas) {
        this.id = id;
        this.produtos = produtos;
        this.vendas = vendas;
    }
    public Vendaproduto(VendaprodutoId id, Produtos produtos, Vendas vendas, int iaaQuantidade, Double iaaValor, Double iaaDesconto) {
       this.id = id;
       this.produtos = produtos;
       this.vendas = vendas;
       this.iaaQuantidade = iaaQuantidade;
       this.iaaValor = iaaValor;
       this.iaaDesconto = iaaDesconto;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iaaIdVenda", column=@Column(name="iaaIdVenda", nullable=false) ), 
        @AttributeOverride(name="iaaIdProduto", column=@Column(name="iaaIdProduto", nullable=false) ), 
        @AttributeOverride(name="iaaIdVendaProdutos", column=@Column(name="iaaIdVendaProdutos", nullable=false) ) } )
    public VendaprodutoId getId() {
        return this.id;
    }
    
    public void setId(VendaprodutoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iaaIdProduto", nullable=false, insertable=false, updatable=false)
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iaaIdVenda", nullable=false, insertable=false, updatable=false)
    public Vendas getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Vendas vendas) {
        this.vendas = vendas;
    }

    
    @Column(name="iaaQuantidade")
    public int getIaaQuantidade() {
        return this.iaaQuantidade;
    }
    
    public void setIaaQuantidade(int iaaQuantidade) {
        this.iaaQuantidade = iaaQuantidade;
    }

    
    @Column(name="iaaValor", precision=10)
    public Double getIaaValor() {
        return this.iaaValor;
    }
    
    public void setIaaValor(Double iaaValor) {
        this.iaaValor = iaaValor;
    }

    
    @Column(name="iaaDesconto", precision=10)
    public Double getIaaDesconto() {
        return this.iaaDesconto;
    }
    
    public void setIaaDesconto(Double iaaDesconto) {
        this.iaaDesconto = iaaDesconto;
    }

}


