package bean;
// Generated 14/12/2025 15:05:49 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vendas generated by hbm2java
 */
@Entity
@Table(name="vendas"
    ,catalog="db_isadora_amaral"
)
public class Vendas  implements java.io.Serializable {


     private int iaaIdVenda;
     private Clientes iaaIdClientes;
     private Usuarios iaaIdUsuarios;
     private Date iaaDataVenda;
     private Double iaaTotal;
     private String iaaStatus;
     private String iaaFormaPagamento;
     private Date iaaDataEntrega;

    public Vendas() {
    }

	
    public Vendas(int iaaIdVenda, Clientes iaaIdClientes, Usuarios iaaIdUsuarios, Double iaaTotal, String iaaStatus) {
        this.iaaIdVenda = iaaIdVenda;
        this.iaaIdClientes = iaaIdClientes;
        this.iaaIdUsuarios = iaaIdUsuarios;
        this.iaaTotal = iaaTotal;
        this.iaaStatus = iaaStatus;
    }
    public Vendas(int iaaIdVenda, Clientes iaaIdClientes, Usuarios iaaIdUsuarios, Date iaaDataVenda, Double iaaTotal, String iaaStatus, String iaaFormaPagamento, Date iaaDataEntrega) {
       this.iaaIdVenda = iaaIdVenda;
       this.iaaIdClientes = iaaIdClientes;
       this.iaaIdUsuarios = iaaIdUsuarios;
       this.iaaDataVenda = iaaDataVenda;
       this.iaaTotal = iaaTotal;
       this.iaaStatus = iaaStatus;
       this.iaaFormaPagamento = iaaFormaPagamento;
       this.iaaDataEntrega = iaaDataEntrega;
    }
   
     @Id 

    
    @Column(name="iaaIdVenda", unique=true, nullable=false)
    public int getIaaIdVenda() {
        return this.iaaIdVenda;
    }
    
    public void setIaaIdVenda(int iaaIdVenda) {
        this.iaaIdVenda = iaaIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iaaIdCliente", nullable=false)
    public Clientes getIaaIdClientes() {
        return this.iaaIdClientes;
    }
    
    public void setIaaIdClientes(Clientes iaaIdClientes) {
        this.iaaIdClientes = iaaIdClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iaaIdUsuarios", nullable=false)
    public Usuarios getIaaIdUsuarios() {
        return this.iaaIdUsuarios;
    }
    
    public void setIaaIdUsuarios(Usuarios iaaIdUsuarios) {
        this.iaaIdUsuarios = iaaIdUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="iaaDataVenda", length=10)
    public Date getIaaDataVenda() {
        return this.iaaDataVenda;
    }
    
    public void setIaaDataVenda(Date iaaDataVenda) {
        this.iaaDataVenda = iaaDataVenda;
    }

    
    @Column(name="iaaTotal", nullable=false, precision=10)
    public Double getIaaTotal() {
        return this.iaaTotal;
    }
    
    public void setIaaTotal(Double iaaTotal) {
        this.iaaTotal = iaaTotal;
    }

    
    @Column(name="iaaStatus", nullable=false, length=20)
    public String getIaaStatus() {
        return this.iaaStatus;
    }
    
    public void setIaaStatus(String iaaStatus) {
        this.iaaStatus = iaaStatus;
    }

    
    @Column(name="iaaFormaPagamento", length=50)
    public String getIaaFormaPagamento() {
        return this.iaaFormaPagamento;
    }
    
    public void setIaaFormaPagamento(String iaaFormaPagamento) {
        this.iaaFormaPagamento = iaaFormaPagamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="iaaDataEntrega", length=10)
    public Date getIaaDataEntrega() {
        return this.iaaDataEntrega;
    }
    
    public void setIaaDataEntrega(Date iaaDataEntrega) {
        this.iaaDataEntrega = iaaDataEntrega;
    }

}


