package bean;
// Generated 08/10/2025 17:03:02 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vendas generated by hbm2java
 */
@Entity
@Table(name="vendas"
    ,catalog="db_isadora_amaral"
)
public class Vendas  implements java.io.Serializable {


     private int iaaIdVenda;
     private Date iaaDataVenda;
     private int iaaCliente;
     private double iaaTotal;
     private String iaaStatus;
     private String iaaFormaPagamento;
     private Date iaaDataEntrega;

    public Vendas() {
    }

	
    public Vendas(int iaaIdVenda, int iaaCliente, double iaaTotal, String iaaStatus) {
        this.iaaIdVenda = iaaIdVenda;
        this.iaaCliente = iaaCliente;
        this.iaaTotal = iaaTotal;
        this.iaaStatus = iaaStatus;
    }
    public Vendas(int iaaIdVenda, Date iaaDataVenda, int iaaCliente, double iaaTotal, String iaaStatus, String iaaFormaPagamento, Date iaaDataEntrega) {
       this.iaaIdVenda = iaaIdVenda;
       this.iaaDataVenda = iaaDataVenda;
       this.iaaCliente = iaaCliente;
       this.iaaTotal = iaaTotal;
       this.iaaStatus = iaaStatus;
       this.iaaFormaPagamento = iaaFormaPagamento;
       this.iaaDataEntrega = iaaDataEntrega;
    }
   
     @Id 

    
    @Column(name="iaaIdVenda", unique=true, nullable=false)
    public int getIaaIdVenda() {
        return this.iaaIdVenda;
    }
    
    public void setIaaIdVenda(int iaaIdVenda) {
        this.iaaIdVenda = iaaIdVenda;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="iaaDataVenda", length=10)
    public Date getIaaDataVenda() {
        return this.iaaDataVenda;
    }
    
    public void setIaaDataVenda(Date iaaDataVenda) {
        this.iaaDataVenda = iaaDataVenda;
    }

    
    @Column(name="iaaCliente", nullable=false)
    public int getIaaCliente() {
        return this.iaaCliente;
    }
    
    public void setIaaCliente(int iaaCliente) {
        this.iaaCliente = iaaCliente;
    }

    
    @Column(name="iaaTotal", nullable=false, precision=22, scale=0)
    public double getIaaTotal() {
        return this.iaaTotal;
    }
    
    public void setIaaTotal(double iaaTotal) {
        this.iaaTotal = iaaTotal;
    }

    
    @Column(name="iaaStatus", nullable=false, length=20)
    public String getIaaStatus() {
        return this.iaaStatus;
    }
    
    public void setIaaStatus(String iaaStatus) {
        this.iaaStatus = iaaStatus;
    }

    
    @Column(name="iaaFormaPagamento", length=50)
    public String getIaaFormaPagamento() {
        return this.iaaFormaPagamento;
    }
    
    public void setIaaFormaPagamento(String iaaFormaPagamento) {
        this.iaaFormaPagamento = iaaFormaPagamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="iaaDataEntrega", length=10)
    public Date getIaaDataEntrega() {
        return this.iaaDataEntrega;
    }
    
    public void setIaaDataEntrega(Date iaaDataEntrega) {
        this.iaaDataEntrega = iaaDataEntrega;
    }




}


