package bean;
// Generated 14/12/2025 15:05:49 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VendaprodutoId generated by hbm2java
 */
@Embeddable
public class VendaprodutoId  implements java.io.Serializable {


     private int iaaIdVenda;
     private int iaaIdProduto;
     private int iaaIdVendaProdutos;

    public VendaprodutoId() {
    }

    public VendaprodutoId(int iaaIdVenda, int iaaIdProduto, int iaaIdVendaProdutos) {
       this.iaaIdVenda = iaaIdVenda;
       this.iaaIdProduto = iaaIdProduto;
       this.iaaIdVendaProdutos = iaaIdVendaProdutos;
    }
   


    @Column(name="iaaIdVenda", nullable=false)
    public int getIaaIdVenda() {
        return this.iaaIdVenda;
    }
    
    public void setIaaIdVenda(int iaaIdVenda) {
        this.iaaIdVenda = iaaIdVenda;
    }


    @Column(name="iaaIdProduto", nullable=false)
    public int getIaaIdProduto() {
        return this.iaaIdProduto;
    }
    
    public void setIaaIdProduto(int iaaIdProduto) {
        this.iaaIdProduto = iaaIdProduto;
    }


    @Column(name="iaaIdVendaProdutos", nullable=false)
    public int getIaaIdVendaProdutos() {
        return this.iaaIdVendaProdutos;
    }
    
    public void setIaaIdVendaProdutos(int iaaIdVendaProdutos) {
        this.iaaIdVendaProdutos = iaaIdVendaProdutos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendaprodutoId) ) return false;
		 VendaprodutoId castOther = ( VendaprodutoId ) other; 
         
		 return (this.getIaaIdVenda()==castOther.getIaaIdVenda())
 && (this.getIaaIdProduto()==castOther.getIaaIdProduto())
 && (this.getIaaIdVendaProdutos()==castOther.getIaaIdVendaProdutos());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIaaIdVenda();
         result = 37 * result + this.getIaaIdProduto();
         result = 37 * result + this.getIaaIdVendaProdutos();
         return result;
   }   


}


