package bean;
// Generated 08/10/2025 17:03:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VendaProduto generated by hbm2java
 */
@Entity
@Table(name="venda_produto"
    ,catalog="db_isadora_amaral"
)
public class VendaProduto  implements java.io.Serializable {


     private int iaaIdVendaProdutos;
     private int iaaIdPedido;
     private int iaaIdProduto;
     private int iaaQuantidade;
     private double iaaValor;
     private double iaaDesconto;
     private String iaaObservacao;

    public VendaProduto() {
    }

    public VendaProduto(int iaaIdVendaProdutos, int iaaIdPedido, int iaaIdProduto, int iaaQuantidade, double iaaValor, double iaaDesconto, String iaaObservacao) {
       this.iaaIdVendaProdutos = iaaIdVendaProdutos;
       this.iaaIdPedido = iaaIdPedido;
       this.iaaIdProduto = iaaIdProduto;
       this.iaaQuantidade = iaaQuantidade;
       this.iaaValor = iaaValor;
       this.iaaDesconto = iaaDesconto;
       this.iaaObservacao = iaaObservacao;
    }
   
     @Id 

    
    @Column(name="iaaIdVenda_Produtos", unique=true, nullable=false)
    public int getIaaIdVendaProdutos() {
        return this.iaaIdVendaProdutos;
    }
    
    public void setIaaIdVendaProdutos(int iaaIdVendaProdutos) {
        this.iaaIdVendaProdutos = iaaIdVendaProdutos;
    }

    
    @Column(name="iaaIdPedido", nullable=false)
    public int getIaaIdPedido() {
        return this.iaaIdPedido;
    }
    
    public void setIaaIdPedido(int iaaIdPedido) {
        this.iaaIdPedido = iaaIdPedido;
    }

    
    @Column(name="iaaIdProduto", nullable=false)
    public int getIaaIdProduto() {
        return this.iaaIdProduto;
    }
    
    public void setIaaIdProduto(int iaaIdProduto) {
        this.iaaIdProduto = iaaIdProduto;
    }

    
    @Column(name="iaaQuantidade", nullable=false)
    public int getIaaQuantidade() {
        return this.iaaQuantidade;
    }
    
    public void setIaaQuantidade(int iaaQuantidade) {
        this.iaaQuantidade = iaaQuantidade;
    }

    
    @Column(name="iaaValor", nullable=false, precision=22, scale=0)
    public double getIaaValor() {
        return this.iaaValor;
    }
    
    public void setIaaValor(double iaaValor) {
        this.iaaValor = iaaValor;
    }

    
    @Column(name="iaaDesconto", nullable=false, precision=22, scale=0)
    public double getIaaDesconto() {
        return this.iaaDesconto;
    }
    
    public void setIaaDesconto(double iaaDesconto) {
        this.iaaDesconto = iaaDesconto;
    }

    
    @Column(name="iaaObservacao", nullable=false, length=100)
    public String getIaaObservacao() {
        return this.iaaObservacao;
    }
    
    public void setIaaObservacao(String iaaObservacao) {
        this.iaaObservacao = iaaObservacao;
    }




}


